### ISSUE TITLE
No permission to run a command from the sandbox

### ISSUE THREAD

**Issue by sticnarf** [t123yh/simple-sandbox#1]
Following the instructions in README, I ran the demo.js:

```
$ sudo node demo/demo.js
Whooops! Error: The child process has reported the following error: The specified path "/opt/sandbox-test/rootfs/sandbox/binary" does not exist.
```

Then, I created `/opt/sandbox-test/rootfs/sandbox/binary` and `/opt/sandbox-test/rootfs/sandbox/working`, and then retry:

```
$ sudo node demo/demo.js
Sandbox started, press enter to stop
Your sandbox finished!{"status":1,"time":656329,"memory":131072,"code":126}
```

The running exits with code `126` which should indicates no permission to run the command.

**Comment by t123yh** [comment]
Check if `nobody` user can access your rootfs. You can do this by `sudo -u nobody -s` and `cd` to that directory. Note that the user must have `x` (execute) permission on every parent directory in order to access the rootfs.

If it doesn't help, you might have to check for the return code of `execve` function call. I'm very sorry that I didn't write a logic to check the return code of `execve`. You can add some lines of code to the `catch` block of `ChildProcess()` in `native/sandbox.cc` to print the error message to Standard Error (you could comment out the redirection of `stderr` stream in line 105 to see the error message directly).
